checkpoint('2018-07-07', scanForPackages = TRUE)
rm(list = ls()); gc()
source('rscripts/obter_propostas_camara.R')
rm(list = ls()); gc()
source('rscripts/obter_dados_camara.R')
rm(list = ls()); gc()
source('rscripts/obter_dados_senado.R')
rm(list = ls()); gc()
source('rscripts/combinar_tramitacoes.R')
rm(list = ls()); gc()
source('rscripts/gera_dados_treinamento_teste.R')
rm(list = ls()); gc()
source('rscripts/treina_modelo_final.R', echo = TRUE)
rm(list = ls()); gc()
source('rscripts/cria_json.R', echo = TRUE)
