checkpoint('2017-12-07', scanForPackages = FALSE)
rm(list = ls()); gc()
source('rscripts/obter_propostas_camara.R')
rm(list = ls()); gc()
source('rscripts/obter_dados_camara.R')
rm(list = ls()); gc()
source('rscripts/obter_dados_senado.R')
rm(list = ls()); gc()
source('rscripts/combinar_tramitacoes.R')
rm(list = ls()); gc()
source('rscripts/gera_dados_treinamento_teste.R')
rm(list = ls()); gc()
source('rscripts/modelos.R', echo = TRUE)
rm(list = ls()); gc()
source('rscripts/cria_json.R', echo = TRUE)
